name: 'Retrieve-and-Pull-Request-Action'
description: 'Retrieve Source from Salesforce and Create a Pull Request with Changes'
inputs:
  salesforce_sfdx_auth_url:
    description: >
      The Auth URL of the salesforce instance and user example: force://PlatformCLI::XXXXXXXXX_XXXXXXX@xxxx.my.salesforce.com.
    defualt: auth-url 
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.salesforce_sfdx_auth_url }}
